---
abstract: 'Heroku API'
author:
  - 'Glen Hinkle'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Heroku
requires:
  IO::Socket::SSL: 1.75
  Mojolicious: 3.0
resources:
  repository: git://github.com/tempire/net-heroku.git
version: 0.09
